# Below one does work... look at the version!

# Wordpress for LOCAL development
version: "3"

services:
  # Database - Change SERVICES name? to DB-WS-01 ? an so on...
  database:
    image: mysql:5.7 # CANGE FOR MARIA DB?
    # CHANGE FOR EVERY WEB SITE!!!
    container_name: "${PRODUCTION_NAME}_database"
    # command:
    #   - "--character-set-server=utf8"
    #   - "--collation-server=utf8_unicode_ci"
    volumes: ["./db_data:/var/lib/mysql"]
    restart: always
    environment:
      # CHANGE FOR EVERY WEB SITE!!!
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - website01
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    # CHANGE FOR EVERY WEB SITE!!!
    container_name: "${PRODUCTION_NAME}_phpmyadmin"
    restart: always
    ports:
      - "${LOCAL_PORT_DB_GUI}:80"
    environment:
      PMA_HOST: database
      # CHANGE FOR EVERY WEB SITE!!! : It has to be in sync with DB
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - website01
  # Wordpress
  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    # CHANGE FOR VERY WEB SITE!!!
    container_name: "${PRODUCTION_NAME}_wordpress"
    ports:
      - "${LOCAL_SERVER_PORT}:80"
    restart: always
    volumes: ["./wordpress/:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}:3306" # Default port for mysql!
      # CHANGE FOR EVERY WEB SITE!!! : It has to be in sync with DB
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    networks:
      - website01
networks:
  website01:
volumes:
  db_data:
  wordpress:
